### PR TITLE
Add file id provider interface

### LINKED ISSUE #71: Expose interface for custom ID provider or make CreateFileAsync of TusDiskStore virtual
I think the title says it all.
This is useful if custom ID's are needed.

I need for example Guid.NewGuid().ToString("D");

### PR DESCRIPTION
**Pull request by SnGmng**
This intends to finnaly close #71

### CODE REVIEW

**Comment by SnGmng** [comment]
I decided to show some examples what this PR is useful for.
For example you can use your database as a file id provider:
```csharp
public class DatabaseFileIdProvider : ITusFileIdProvider
{
    private readonly ApplicationDbContext _db;

    /// <summary>
    /// Creates a new DatabaseFileIdProvider
    /// </summary>
    public DatabaseFileIdProvider(ApplicationDbContext db)
    {
        _db = db;
    }

    /// <inheritdoc />
    public string CreateId()
    {
        FileEntity file = new FileEntity();
        _db.Files.Add(file);
        _db.Files.SaveChanges();
        return file.Id;
    }

    /// <inheritdoc />
    public bool ValidateId(string fileId)
    {
        return _db.Files.Exists(fileId);
    }
}
```
Or you can inherit from another file id provider and just add your database implementation:
```csharp
public class DatabaseGuidProvider : TusGuidProvider
{
    private readonly ApplicationDbContext _db;

    /// <summary>
    /// Creates a new DatabaseFileIdProvider
    /// </summary>
    public DatabaseGuidProvider(ApplicationDbContext db) : base()
    {
        _db = db;
    }

    /// <inheritdoc />
    public override string CreateId()
    {
        FileEntity file = new FileEntity();
        file.Id = base.CreateId();

        _db.Files.Add(file);
        _db.Files.SaveChanges();
        return file.Id;
    }

    /// <inheritdoc />
    public override bool ValidateId(string fileId)
    {
        return base.ValidateId(fileId) && _db.Files.Exists(fileId);
    }
}
```
To use the file id providers, they can be passed to TusDataStore's constructor which is DI friendly.

**Comment by smatsson** [comment]
Hi,

Thanks for the PR! Looks good overall and I like that you added examples. Some notes:

* There are no tests. We should at least test that TusDiskStore uses the provided `ITusFileIdProvider` and that the providers returns valid values for a couple of formats.
* What's the entropy of `TusBase64IdProvider`? Is it guaranteed to be unique for every call to `Create`? I think that we should keep tusdotnet "safe" out of the box and not add things that might break, e.g. if there is a chance that the provider creates two identical IDs, that would be a big problem.
* [In earlier discussions](https://github.com/tusdotnet/tusdotnet/issues/71) it was mentioned that we should provide the file metadata to the `Create` method to allow developers to create IDs based on provided metadata. Is there a reason that this was not added? I can see some drawbacks to this approach as some developers might just use whatever the client sent them without further thought. On the other hand it would add a very powerful feature if used together with user access control and/or separate storage areas (i.e. disk paths per user).
* Since this feature can be used to create whatever ID the developer wants I think we also need to update the internal locking mechanism. We currently use an [in memory file lock](https://github.com/tusdotnet/tusdotnet/blob/master/Source/tusdotnet/Helpers/InMemoryFileLock.cs) that requires each ID to be unique. This isn't necessarily true if the developer can specify IDs however they want. User A and User B might have separate storage areas but if the two users create a ID that is the same, only one can currently write the file and the other would have to wait.
* The examples are very good! Once merged, feel free to add a page in [the wiki repo](https://github.com/tusdotnet/tusdotnet.wikisource) on how to write custom file id providers.

**Comment by SnGmng** [comment]
Hi,

Thanks for your feedback!
Tests and UploadMetadata is a good idea, i will implement them in my next commit.

The entropy of `TusBase64IdProvider` is pretty high, because it uses BCryptGenRandom (Windows) or OpenSSL's random number generator (Linux) which are both cryptograpically secure.

The probability of duplicates of `TusBase64IdProvider` in the default configuartion (16 bytes) is comparable with GUID.

- The probability of a duplicate numeric GUID is 1 in 10^32
- The probability of a duplicate Base64Id (16 bytes) is 1 in 64^16
- The probability of a duplicate Base64Id of length n is 1 in 64^n

But the probability of a duplicate in both file id providers is never completely zero, exept if you check if a duplicate exists (either in the db or in the file system)
So i propose following solution:
```csharp
public interface ITusFileIdProvider
{
    string CreateId();
    bool ValidateId();
}

public interface ITusUniqueFileIdProvider : ITusFileIdProvider
{
    // or call this method "IsUnique" or whatever you prefer
    bool CheckDuplicate();
}
```
And when creating ids in in TusDiskStore:
```csharp
Func<string, bool> checkDuplicate;
if (_fileIdProvider is ITusUniqueFileIdProvider uniqueProvider)
{
    // 
    checkDuplicate = uniqueProvider.CheckDuplicate;
}
else 
{
    // fileId is not guaraneed to be unique but still check the file system
    // the id will only be unique in the file system, not unique across multiple locations/servers,
    // which is sufficient for most users.
    checkDuplicate = (id) => File.Exists(location + id)
}

string fileId = _fileIdProvider.Create(fileId);
for (int retries = 0; retries < 5 && checkDuplicate(fileId); retries++)
{
     fileId = uniqueProvider.Create(fileId);
}

if (retries == 5)
{
      throw new Exception($"{uniqueProvider.GetType().FullName} failed to generate unique id (5/5 retries failed)");
}
```
Then, the database implementation will look like this:
```csharp
public class DatabaseFileIdProvider : ITusUniqueFileIdProvider
{
    (...)

    // ids created by the db will never be duplicates
    public bool CheckDuplicate() => false;
}
```
Or the user can provide his own implementation to ensure the id is unique across multiple locations/servers
```csharp
public class DuplicateSafeGuidProvider : TusGuidProvider, ITusUniqueFileIdProvider
{
    public DatabaseGuidProvider() : base() { }

    public bool CheckDuplicate(string fileId)
    {
        // for example, check multiple locations
        return File.Exists(locationA) || File.Exists(locationB);
    }
}
```

The in memory file lock problem can be easily solved by locking the file path instead of the file id.

What are your thoughts about all this?

**Comment by smatsson** [comment]
>The probability of duplicates of TusBase64IdProvider in the default configuartion (16 bytes) is comparable with GUID.

This is definitely good enough. I don't think that we need an extra interface for checking duplicates. The `CreateId` method should be responsible to create unique ids, given the context for where it runs (e.g. per path or per user). The extra interface doesn't bring much but should instead be enforced by docs.

>The in memory file lock problem can be easily solved by locking the file path instead of the file id.

Sounds good. We can't rely on the store being the disk store though so we need to have support for multiple locking providers. Basically just provide an interface that the MemoryLock and others can implement.

**Comment by smatsson** [comment]
Very nice, thanks for the updates! Some thoughts:

* The methods of `ITusFileLock` should probably return `Task<T>` in case one wants to use a database or similar for locks.
* I like the name `AquireFileLock` as it's exactly what is going on when it is called. 👍
* Does `CreateId` of `ITusFileIdProvider` need to support async, e.g. return `Task<T>`? 🤔 
* Should `CreateId` take some parameters, e.g. the metadata provided by the client? This would support some niche cases where each user has it's own folder for storing data and can provide the ID themselves (think dropbox where you reference files by file name).

Overall very nicely done. :) I like the test case that ensures that no duplicates are returned. Maybe we should add that the disk store does a check that the file does not already exist after calling `CreateId` in `CreateFileAsync`? Feel free to give your opinions on the points above. Besides from these thoughts I think this is ready to merge.

**Comment by SnGmng** [comment]
The commit making `ITusFileIdProvider` async resulted in a whole lot of methods needing to be async.
Just wanted to make you aware of that 👍

**Comment by smatsson** [comment]
Thank you for the PR! Well done!

**Pull request merged**
