### PR TITLE
Make metadata keys case insensitive

### PR DESCRIPTION
**Pull request by SasaCetkovic**

### CODE REVIEW

**Comment by smatsson** [comment]
Hi SasaCetkovic, 

Thanks for the PR! Could you please provide some context. What is the use case and what problem is your code change fixing?

**Comment by SasaCetkovic** [comment]
Hi Stefan,

In my case, we have different teams/companies working independently on frontend and backend, working with different naming conventions. This would make things a little less error prone, but it is not much important, just a nice to have feature. We're used to headers being case insensitive, and these metadata are similar.

By the way, thanks for this great work!

**Comment by smatsson** [comment]
I'm glad you like the lib! :) 

I get what you're saying but unfortunately I cannot accept this PR as it would break compatibility with other tus implementations. There is nothing in the protocol about case sensitivity (http://tus.io/protocols/resumable-upload.html#upload-metadata) but other implementations does
not normalize casing, i.e the following is perfectly fine:

```
Upload-Metadata: filename d29ybGRfZG9taW5hdGlvbl9wbGFuLnBkZg==,FILENAME d29ybGRfZG9taW5hdGlvbl9wbGFuLnBkZg==
```

The changes in this PR would break the above request as it would pass through the "All keys MUST be unique" requirement from the spec but then the former of the two keys would be overwritten by the latter.

Based on your use case I would recommend that you write an extension method similar to the one below:

```csharp
public static class ITusFileExtensions
{
	public static async Task<Dictionary<string, Metadata>> GetMetadataIgnoreCaseAsync(this ITusFile file, CancellationToken cancellationToken)
	{
		var metadata = await file.GetMetadataAsync(cancellationToken);
		return new Dictionary<string, Metadata>(metadata, StringComparer.OrdinalIgnoreCase);
	}
}
```

And then replace calls to file.GetMetadataAsync with:
```csharp
var metadata = await file.GetMetadataIgnoreCaseAsync(cancellationToken);
```

**Comment by SasaCetkovic** [comment]
I see. My fail for not looking into other implementations.

Thanks for the feedback!

**Comment by smatsson** [comment]
@SasaCetkovic No worries mate. That's why we are here to keep track of all the nitty gritty details of the protocol and implementations. Hope that my work around is good enough for you :)

**Pull request closed without merging**
